version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
    install:
      - method: pip
        path: .
        extra_requirements:
            - docs