[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openreview-py"
version = "1.45.0"
description = "OpenReview API Python client library"
authors = [{name = "OpenReview Team", email = "info@openreview.net"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "pycryptodome",
    "requests>=2.18.4",
    "future",
    "tqdm",
    "Deprecated",
    "pylatexenc",
    "tld>=0.12",
    "pyjwt",
]

[project.urls]
Homepage = "https://github.com/openreview/openreview-py"

[project.optional-dependencies]
docs = [
    "nbsphinx",
    "sphinx",
    "sphinx_rtd_theme",
    "nbformat"
]

[tool.setuptools.package-data]
"openreview" = ["*"]

[tool.setuptools.packages.find]
include = [
    "openreview",
    "openreview.conference",
    "openreview.profile",
    "openreview.agora",
    "openreview.venue",
    "openreview.venue.configuration",
    "openreview.venue_request",
    "openreview.journal",
    "openreview.journal.journal_request",
    "openreview.stages",
    "openreview.arr",
    "openreview.api"
]
