[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openreview-py"
version = "1.52.1"
description = "OpenReview API Python client library"
authors = [{name = "OpenReview Team", email = "info@openreview.net"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "requests>=2.28,<3.0",
    "numpy>=2.0.0,<3.0",
    "pycryptodome>=3.23,<4.0",
    "litellm>=1.76,<2.0",
    "future>=1.0,<2.0",
    "tqdm>=4.67,<5.0",
    "Deprecated>=1.2,<2.0",
    "pylatexenc>=2.10,<3.0",
    "tld>=0.13,<1.0",
    "pyjwt>=2.8,<3.0",
]

[project.urls]
Homepage = "https://github.com/openreview/openreview-py"

[project.optional-dependencies]
docs = [
    "nbsphinx>=0.9.7,<1.0",
    "sphinx>=8.1.3,<9.0",
    "sphinx_rtd_theme>=3.0.2,<4.0",
    "nbformat>=5.10.4,<6.0",
]

dev = [
    "py>=1.11.0,<2.0",
    "pytest>=8.3,<9.0",
    "selenium>=4.0,<5.0",
    "pytest-selenium>=4.0,<5.0",
]

[tool.setuptools.package-data]
"openreview" = ["*"]

[tool.setuptools.packages.find]
include = [
    "openreview",
    "openreview.conference",
    "openreview.profile",
    "openreview.agora",
    "openreview.venue",
    "openreview.venue_request",
    "openreview.journal",
    "openreview.journal.journal_request",
    "openreview.stages",
    "openreview.arr",
    "openreview.api",
    "openreview.workflows"
]
