from ... import openreview
from ... import tools
import os

class JournalRequest():


    @classmethod
    def get_journal(JournalRequest, client, journal_request_id, setup=False):
        journal_request = client.get_note(journal_request_id)
        venue_id = journal_request.content.get('venue_id', {}).get('value')

        if not venue_id:
            ## the venue id is assigned by the deployment invitation, so the journal is not deployed yet
            return None

        ## the secret key is generated by Journal.setup the first time the journal is
        ## deployed and stored in the venue group content; fall back to the request note
        ## for journals deployed before the key was moved to the group
        secret_key = None
        venue_group = tools.get_group(client, venue_id)
        if venue_group:
            secret_key = (venue_group.content or {}).get('secret_key', {}).get('value')
        if not secret_key:
            secret_key = journal_request.content.get('secret_key', {}).get('value')
        contact_info = journal_request.content['contact_info']['value']
        full_name = journal_request.content['official_venue_name']['value']
        short_name = journal_request.content['abbreviated_venue_name']['value']
        website = journal_request.content['website']['value']
        support_role = journal_request.content['support_role']['value']
        editors = journal_request.content['editors']['value']
        assignment_delay = journal_request.content.get('settings', {}).get('value', {}).get('assignment_delay', 5)
        settings = journal_request.content.get('settings', {}).get('value', {})
        submission_name = journal_request.content.get('settings', {}).get('value', {}).get('submission_name')

        journal = openreview.journal.Journal(client, venue_id, secret_key, contact_info, full_name, short_name, website, submission_name, settings)
        journal.request_form_id = journal_request_id

        if setup:
            journal.setup(support_role, editors=editors, assignment_delay=assignment_delay)

        return journal


    def __init__(self, client, support_group_id):
        self.support_group_id = support_group_id
        self.support_group = tools.get_group(client, self.support_group_id)
        self.client = client
        self.meta_invitation_id = f'{support_group_id}/-/Edit'

    def post_invitation_edit(self, invitation):
        return self.client.post_invitation_edit(invitations=self.meta_invitation_id,
            readers=['~Super_User1'],
            writers=['~Super_User1'],
            signatures=['~Super_User1'],
            invitation=invitation,
            replacement=True
        )

    def get_request_form_content(self):

        return {
            'title': {
                'description': 'Used for display purposes. This is copied from the Official Venue Name',
                'order': 1,
                'value': {
                    'param': {
                        'type': 'string',
                        'const': '${2/official_venue_name/value}',
                        'hidden': True
                    }
                }
            },
            'official_venue_name': {
                'description': 'This will appear in your journal\'s OpenReview homepage.',
                'order': 2,
                'value' : {
                    'param': {
                        'type': 'string'
                    }
                }
            },
            'abbreviated_venue_name': {
                'description': 'This will be used to identify your journal in OpenReview and in email subject lines',
                'order': 3,
                'value' : {
                    'param': {
                        'type': 'string'
                    }
                }
            },
            'contact_info': {
                'description': 'Single point of contact email address, which will be displayed on the journal homepage',
                'order': 4,
                'value' : {
                    'param': {
                        'type': 'string',
                        'regex': r'([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})'
                    }
                }
            },
            'support_role': {
                'order': 5,
                'value': {
                    'param': {
                        'type': 'string',
                        'regex': r'~.*|([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})'
                    }
                }
            },
            'editors': {
                'order': 6,
                'value': {
                    'param': {
                        'type': 'string[]',
                        'regex': r'~.*|([a-z0-9_\-\.]{1,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{1,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})',
                    }
                }
            },
            'website': {
                'order': 7,
                'value': {
                    'param': {
                        'type': 'string'
                    }
                }
            },
            'settings': {
                'order': 8,
                'description': 'Journal settings in JSON format. See the available settings and their descriptions in the documentation: https://docs.openreview.net/getting-started/hosting-a-venue-on-openreview/customizing-settings-and-forms-for-a-journal#journal-settings',
                'value': {
                    'param': {
                        'type': 'json',
                        'optional': True,
                        'default': {
                            'submission_name': 'Submission',
                            'assignment_delay': 5,
                            'submission_public': True,
                            'submission_license': 'CC BY-SA 4.0',
                            'author_anonymity': True,
                            'AE_anonymity': False,
                            'reviewer_to_reviewer_anonymity': False,
                            'release_submission_after_acceptance': True,
                            'expertise_model': 'specter2+scincl',
                            'external_reviewers': True,
                            'expert_reviewers': False,
                            'archived_action_editors': False,
                            'archived_reviewers': False,
                            'number_of_reviewers': 3,
                            'reviewers_max_papers': 6,
                            'action_editors_max_papers': 12,
                            'ae_max_active_submissions': 2,
                            'ae_recommendation_period': 1,
                            'under_review_approval_period': 1,
                            'reviewer_assignment_period': 1,
                            'review_period': 2,
                            'discussion_period': 2,
                            'recommendation_period': 2,
                            'decision_period': 1,
                            'camera_ready_period': 4,
                            'camera_ready_verification_period': 1,
                            'assignment_delay_after_submitted_review': 0,
                            'max_solicit_review_per_month': 0,
                            'skip_ac_recommendation': False,
                            'skip_official_recommendation': False,
                            'skip_reviewer_responsibility_acknowledgement': False,
                            'skip_reviewer_assignment_acknowledgement': False,
                            'skip_camera_ready_revision': False,
                            'eic_submission_notification': False,
                            'eic_decision_notification': False,
                            'enable_blocked_authors': False,
                            'show_conflict_details': False,
                            'has_publication_chairs': False,
                            'archive_previous_year_assignments': False,
                            'journal_to_conference_certification': False,
                            'certifications': [],
                            'eic_certifications': [],
                            'event_certifications': [],
                            'submission_length': [],
                            'website_urls': {},
                            'submission_additional_fields': {},
                            'review_additional_fields': {},
                            'official_recommendation_additional_fields': {},
                            'official_recommendation_additional_validation': {},
                            'official_recommendation_description': '',
                            'decision_additional_fields': {},
                            'issn': None,
                            'min_profile_valid_state': None,
                            'submission_deadline': None
                        }
                    }
                }
            }
        }

    def setup_journal_request(self):

        journal_request_content = self.get_request_form_content()

        with open(os.path.join(os.path.dirname(__file__), 'process/request_form_process.py')) as f:
            content = f.read()
            content = content.replace("SUPPORT_GROUP = ''", "SUPPORT_GROUP = '" + self.support_group_id + "'")

            ## the request form only creates pending requests and notifies the EICs; all
            ## editing goes through the per-request Revision invitation and the journal
            ## is created by the Deployment invitation
            invitation = openreview.api.Invitation(
                id = f'{self.support_group_id}/-/Journal_Request',
                invitees = ['~'],
                readers = ['everyone'],
                writers = [],
                signatures = ['~Super_User1'],
                edit = {
                    'signatures': { 
                        'param': { 
                            'items': [
                                { 'prefix': '~.*', 'optional': True },
                                { 'value': self.support_group_id, 'optional': True}
                            ]
                        }
                    },
                    'writers': ['${2/note/writers}'],
                    'readers': ['${2/note/readers}'],
                    'note': {
                        'signatures': ['${3/signatures}'],
                        'readers': [self.support_group_id, '${2/content/editors/value}'],
                        'writers': [self.support_group_id, '${2/content/editors/value}'],
                        'content': journal_request_content
                    }
                },
                process = content
            )


            self.post_invitation_edit(invitation = invitation)

        self.setup_deployment_invitation()

    def setup_deployment_invitation(self):

        deploy_invitation_id = f'{self.support_group_id}/-/Journal_Request_Deployment'

        with open(os.path.join(os.path.dirname(__file__), 'process/deploy_process.py')) as f:
            content = f.read()
            content = content.replace("SUPPORT_GROUP = ''", "SUPPORT_GROUP = '" + self.support_group_id + "'")

            with open(os.path.join(os.path.dirname(__file__), 'process/deploymentPreprocess.js')) as pre_f:
                preprocess = pre_f.read()

            invitation = openreview.api.Invitation(
                id = deploy_invitation_id,
                invitees = [self.support_group_id],
                readers = [self.support_group_id],
                writers = [self.support_group_id],
                signatures = ['~Super_User1'],
                edit = {
                    'signatures': {
                        'param': {
                            'items': [ { 'value': self.support_group_id, 'optional': True } ]
                        }
                    },
                    'ddate': {
                        'param': {
                            'range': [ 0, 9999999999999 ],
                            'optional': True,
                            'deletable': True
                        }
                    },
                    'readers': [self.support_group_id, '${2/note/content/venue_id/value}'],
                    'writers': [self.support_group_id],
                    'note': {
                        'id': {
                            'param': {
                                'withInvitation': f'{self.support_group_id}/-/Journal_Request'
                            }
                        },
                        'readers': [self.support_group_id, '${2/content/venue_id/value}', '${2/content/venue_id/value}/Action_Editors'],
                        'writers': [self.support_group_id, '${2/content/venue_id/value}'],
                        'content': {
                            'venue_id': {
                                'description': 'Journal venue id',
                                'value': {
                                    'param': {
                                        'type': 'string',
                                        'regex': '.*'
                                    }
                                }
                            }
                        }
                    }
                },
                preprocess = preprocess,
                process = content
            )

            self.post_invitation_edit(invitation = invitation)

    def setup_revision_invitation(self, note_id):

        note = self.client.get_note(note_id)
        venue_id = note.content.get('venue_id', {}).get('value')
        revision_invitation_id = f'{self.support_group_id}/Journal_Request' + str(note.number) + '/-/Revision'

        if venue_id:
            ## the journal is deployed: the venue groups edit the request
            invitees = [venue_id, self.support_group_id]
            signature_items = [
                { 'prefix': '~.*', 'optional': True },
                { 'value': venue_id, 'optional': True },
                { 'value': self.support_group_id, 'optional': True }
            ]
            edit_readers = [self.support_group_id, venue_id]
        else:
            ## the journal is not deployed yet: the editors listed in the form edit the request
            editors = note.content['editors']['value']
            invitees = [self.support_group_id] + editors
            signature_items = [
                { 'prefix': '~.*', 'optional': True },
                { 'value': self.support_group_id, 'optional': True }
            ]
            edit_readers = [self.support_group_id] + editors

        with open(os.path.join(os.path.dirname(__file__), 'process/revision_process.py')) as f:
            content = f.read()
            invitation = openreview.api.Invitation(
                id = revision_invitation_id,
                invitees = invitees,
                readers = invitees,
                writers = [],
                signatures = ['~Super_User1'],
                edit = {
                    'signatures': {
                        'param': {
                            'items': signature_items
                        }
                    },
                    'writers': edit_readers,
                    'readers': edit_readers,
                    'note': {
                        'id': note.id,
                        'signatures': ['${3/signatures}'],
                        'content': self.get_request_form_content()
                    }
                },
                process = content
            )

            self.post_invitation_edit(invitation = invitation)

    def setup_journal_group(self, note_id):

        note = self.client.get_note(note_id)
        self.client.post_group_edit(
            invitation = self.meta_invitation_id,
            readers = [self.support_group_id],
            writers = [self.support_group_id],
            signatures = [self.support_group_id.split('/')[0]],
            group = openreview.api.Group(
                id = f'{self.support_group_id}/Journal_Request{note.number}',
                readers = [self.support_group_id],
                writers = [self.support_group_id],
                signatures = [self.support_group_id.split('/')[0]],                
            )
        )

    def setup_comment_invitation(self, note_id, action_editors_id=None):

        note = self.client.get_note(note_id)
        venue_id = note.content['venue_id']['value']
        request_comment_invitation_id =  f'{self.support_group_id}/Journal_Request' + str(note.number) + '/-/Comment'

        with open(os.path.join(os.path.dirname(__file__), 'process/comment_process.py')) as f:
            content = f.read()
            content = content.replace("SUPPORT_GROUP = ''", "SUPPORT_GROUP = '" + self.support_group_id + "'")
            content = content.replace("VENUE_ID = ''", "VENUE_ID = '" + venue_id + "'")
            invitation = openreview.api.Invitation(
                id = request_comment_invitation_id,
                invitees = [venue_id, self.support_group_id],
                readers = [venue_id, self.support_group_id],
                writers = [],
                signatures = [venue_id],
                edit = {
                    'signatures': { 
                        'param': { 
                            'items': [
                                { 'prefix': '~.*', 'optional': True },
                                { 'value': venue_id, 'optional': True},
                                { 'value': self.support_group_id, 'optional': True}
                            ]
                        }
                    },
                    'writers': [self.support_group_id, venue_id],
                    'readers': [self.support_group_id, venue_id],
                    'note': {
                        'id': {
                            'param': {
                                'withInvitation': request_comment_invitation_id,
                                'optional': True
                            }
                        },
                        'signatures': ['${3/signatures}'],
                        'readers': { 'param': { 'enum': [self.support_group_id, venue_id, '~.*'] }},
                        'writers': [self.support_group_id, venue_id],
                        'forum': note.id,
                        'replyto': { 'param': { 'withForum': note.id }},
                        'content': {
                            'title': {
                                'description': 'Brief summary of your comment.',
                                'order': 1,
                                'value': {
                                    'param': {
                                        'type': 'string',
                                        'regex': '.{1,500}'
                                    }
                                }
                            },
                            'comment': {
                                'description': 'Your comment or reply (max 200000 characters).',
                                'order': 2,
                                'value' : {
                                    'param': {
                                        'type': 'string',
                                        'maxLength': 200000,
                                        'input': 'textarea',
                                        'markdown': True
                                    }
                                }
                            }
                        }
                    }
                },
                process = content
            )

            return self.post_invitation_edit(invitation = invitation)

    def setup_recruitment_invitations(self, note_id, ae_template=None, reviewer_template=None):

        note = self.client.get_note(note_id)
        short_name = note.content['abbreviated_venue_name']['value']
        venue_id = note.content['venue_id']['value']

        default_recruitment_template = '''Dear {{fullname}},

You have been nominated by the program chair committee of {short_name} to serve as {{role}}.

{{invitation_url}}

Cheers!'''.replace('{short_name}', short_name)

        recruitment_content = {
            'title': {
                'order': 1,
                'value': 'Recruitment'
            },
            'invitee_details': {
                'description': 'Enter a list of invitees with one per line. Either tilde IDs (∼Captain_America1), emails (captain_rogers@marvel.com), or email,name pairs (captain_rogers@marvel.com, Captain America) expected. If only an email address is provided for an invitee, the recruitment email is addressed to "Dear invitee". Do not use parentheses in your list of invitees.',
                'order': 3,
                'value' : {
                    'param': {
                        'type': 'string',
                        'maxLength': 50000,
                        'input': 'textarea'
                    }
                }
            },
            'email_subject': {
                'description': 'Please carefully review the email subject for the recruitment emails. Make sure not to remove the parenthesized tokens.',
                'order': 4,
                'value' : {
                    'param': {
                        'type': 'string',
                        'default': '[{short_name}] Invitation to serve as {{role}} for {short_name}'.replace('{short_name}', short_name)
                    }
                }
            },
            'email_content': {
                'description': 'Please carefully review the template below before you click submit to send out recruitment emails. Make sure not to remove the parenthesized tokens.',
                'order': 5,
                'value' : {
                    'param': {
                        'type': 'string',
                        'maxLength': 100000,
                        'input': 'textarea',
                        'default': default_recruitment_template,
                        'markdown': True
                    }
                }
            }
        }

        #setup ae recruitment
        if ae_template:
            recruitment_content['email_content']['value']['param']['default'] = ae_template


        invitation_id = f'{self.support_group_id}/Journal_Request' + str(note.number) + '/-/Action_Editor_Recruitment'
        existing_invitation = openreview.tools.get_invitation(self.client, invitation_id)

        if not existing_invitation or (ae_template and ae_template != existing_invitation.edit['note']['content']['email_content']['value']['param']['default']):
            with open(os.path.join(os.path.dirname(__file__), 'process/recruitment_process.py')) as f:
                content = f.read()
                content = content.replace("SUPPORT_GROUP = ''", "SUPPORT_GROUP = '" + self.support_group_id + "'")
                invitation = openreview.api.Invitation(
                    id = invitation_id,
                    invitees = [venue_id],
                    readers = [venue_id],
                    writers = [],
                    signatures = ['~Super_User1'],
                    edit = {
                    'signatures': { 
                        'param': { 
                            'items': [
                                { 'prefix': '~.*', 'optional': True },
                                { 'value': self.support_group_id, 'optional': True}
                            ]
                        }
                    },
                    'writers': [self.support_group_id, venue_id],
                    'readers': [self.support_group_id, venue_id],
                    'note': {
                        'forum': note.id,
                        'replyto': note.id,
                        'signatures': ['${3/signatures}'],
                        'readers': [self.support_group_id, venue_id],
                        'writers': [self.support_group_id, venue_id],
                        'content': recruitment_content
                    }
                    },
                    process = content
                )

                self.post_invitation_edit(invitation = invitation)

        #setup rev recruitment
        if reviewer_template:
            recruitment_content['email_content']['value']['param']['default'] = reviewer_template

        invitation_id = f'{self.support_group_id}/Journal_Request' + str(note.number) + '/-/Reviewer_Recruitment'
        existing_invitation = openreview.tools.get_invitation(self.client, invitation_id)

        if not existing_invitation or (reviewer_template and reviewer_template != existing_invitation.edit['note']['content']['email_content']['value']['param']['default']):
            with open(os.path.join(os.path.dirname(__file__), 'process/recruitment_process.py')) as f:
                content = f.read()
                content = content.replace("SUPPORT_GROUP = ''", "SUPPORT_GROUP = '" + self.support_group_id + "'")
                invitation = openreview.api.Invitation(
                    id = invitation_id,
                    invitees = [venue_id],
                    readers = [venue_id],
                    writers = [],
                    signatures = ['~Super_User1'],
                    edit = {
                    'signatures': { 
                        'param': { 
                            'items': [
                                { 'prefix': '~.*', 'optional': True },
                                { 'value': self.support_group_id, 'optional': True}
                            ]
                        }
                    },
                    'writers': [self.support_group_id, venue_id],
                    'readers': [self.support_group_id, venue_id],
                    'note': {
                        'forum': note.id,
                        'replyto': note.id,
                        'signatures': ['${3/signatures}'],
                        'readers': [self.support_group_id, venue_id],
                        'writers': [self.support_group_id, venue_id],
                        'content': recruitment_content
                    }
                    },
                    process = content
                )

                self.post_invitation_edit(invitation = invitation)

    def setup_recruitment_by_action_editors(self, note_id, template=None):

        note = self.client.get_note(note_id)
        short_name = note.content['abbreviated_venue_name']['value']
        venue_id = note.content['venue_id']['value']
        recruitment_email_template = '''Dear {{fullname}},

You have been nominated to serve as a reviewer for {short_name} by {{inviter}}.

{{invitation_url}}

Cheers!
{{inviter}}'''.replace('{short_name}', short_name)

        if template:
            recruitment_email_template = template

        recruitment_content = {
            'invitee_name': {
                'description': 'Enter the name of the user you would like to invite.',
                'order': 2,
                'value' : {
                    'param': {
                        'type': 'string',
                        'regex': '^[^,\n]+$'
                    }
                }
            },
            'invitee_email': {
                'description': 'Enter the email or OpenReview profile ID of the user you would like to invite.',
                'order': 2,
                'value' : {
                    'param': {
                        'type': 'string',
                        'regex': '^[^,\n]+$'
                    }
                }
            },
            'email_subject': {
                'description': 'Please carefully review the email subject for the recruitment email. Make sure not to remove the parenthesized tokens.',
                'order': 4,
                'value' : {
                    'param': {
                        'type': 'string',
                        'default': f'[{short_name}] Invitation to act as Reviewer for {short_name}'
                    }
                }
            },
            'email_content': {
                'description': 'Please carefully review the template below before you click submit to send out the recruitment email. Make sure not to remove the parenthesized tokens.',
                'order': 5,
                'value' : {
                    'param': {
                        'type': 'string',
                        'maxLength': 10000,
                        'input': 'textarea',
                        'default': recruitment_email_template
                    }
                }
            }
        }

        invitation_id = f'{self.support_group_id}/Journal_Request' + str(note.number) + '/-/Reviewer_Recruitment_by_AE'
        existing_invitation = openreview.tools.get_invitation(self.client, invitation_id)

        if not existing_invitation or (template and template != existing_invitation.edit['note']['content']['email_content']['value']['param']['default']):

            with open(os.path.join(os.path.dirname(__file__), 'process/ae_recruitment_process.py')) as f:
                content = f.read()
                content = content.replace("SUPPORT_GROUP = ''", "SUPPORT_GROUP = '" + self.support_group_id + "'")
                invitation = openreview.api.Invitation(
                    id = invitation_id,
                    invitees = [f'{venue_id}/Action_Editors'],
                    readers = [f'{venue_id}/Action_Editors'],
                    writers = [],
                    signatures = ['~Super_User1'],
                    edit = {
                        'signatures': { 
                            'param': { 
                                'items': [
                                    { 'prefix': '~.*', 'optional': True },
                                    { 'value': self.support_group_id, 'optional': True}
                                ]
                            }
                        },
                        'writers': [self.support_group_id, venue_id],
                        'readers': [self.support_group_id, venue_id],
                        'note': {
                            'forum': note.id,
                            'replyto': note.id,
                            'signatures': ['${3/signatures}'],
                            'readers': [self.support_group_id, venue_id, '${3/signatures}'],
                            'writers': [self.support_group_id, venue_id],
                            'content': recruitment_content
                        }
                    },
                    process = content
                )

                self.post_invitation_edit(invitation = invitation)
