# This workflow deploys any branch or tag to the production or staging environment.

name: deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: false
        default: 'master'
        type: string
      environment:
        description: 'The environment to deploy to'
        required: false
        default: 'staging'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.inputs.branch }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run deploy script
        run: |
          if [ "$ENVIRONMENT" == "production" ]; then
            instance_prefix='openreview-api'
          else
            instance_prefix='dev-instance'
          fi

          instances=$(gcloud compute instances list | grep "$instance_prefix" | grep RUNNING | tr -s ' ' | cut -d' ' -f1,2)

          instances_arr=(${instances// / })

          instance_names=()
          zones=()
          for i in ${!instances_arr[@]}; do
            if echo "${instances_arr[$i]}" | grep -q "$instance_prefix"; then
              instance_names+=(${instances_arr[$i]})
            else
              zones+=(${instances_arr[$i]})
            fi
          done

          pids=()
          for i in ${!instance_names[@]}; do
            echo Deploying to ${instance_names[$i]}
            gcloud compute ssh --zone ${zones[$i]} openreview@${instance_names[$i]} --command "bash bin/deploy-openreview-py.sh ${BRANCH}" &
            pids+=($!)
          done

          for pid in ${pids[@]}; do
            wait $pid
          done
