name: Publish to TestPyPI and Deploy Dev

on:
  repository_dispatch:
    types: [openreview-py-master-updated]

jobs:
  publish:
    uses: ./.github/workflows/publish-testpypi.yml
    permissions:
      contents: read
      id-token: write

  deploy:
    needs: publish
    uses: ./.github/workflows/deploy-dev.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
